# Use a lightweight Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port used by Streamlit
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "frontUI.py", "--server.port=8501", "--server.enableCORS=false"]



